### ISSUE TITLE
Pause video / Seek inside video

### ISSUE THREAD

**Issue by ehoutsma** [4np/TVGemist#1]
## Short description of the issue

Can't pause the video or search inside the video.

## Issue type

Feature

## What is the expected behaviour?

When I ask siri to pause the video, or press the pause button, the video should pause. When searching the video should skip to the position I request.

## What is actually happening?

Can't pause the video or search inside the video. Must watch the video from start to finish in one go.

## Extra information

Version you are using:  f12c177

tvOS version: 11.0

Xcode version: 9.2

**Comment by 4np** [comment]
Fixed in [0.0.2](https://github.com/4np/TVGemist/releases/tag/0.0.2) :)
