### ISSUE TITLE
App does not build

### ISSUE THREAD

**Issue by dizzzz** [4np/TVGemist#13]
## Short description of the issue

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/1700062/55293737-027a2700-53fa-11e9-8898-ec4196d1568c.png">

app does not build

## Issue type

build issue

## What is the expected behaviour?

app can be compiled

## What is actually happening?

see screenshot 

## Steps to reproduce

build in xcode Version 10.2 (10E125)

## Additional information

Version you are using: latest/develop

tvOS version: latest

Xcode version: Version 10.2 (10E125)

**Comment by 4np** [comment]
Unfortunately the NPO had killed the video server, only DRM FairPlay is possible, of which I don't have the implementation. So unfortunately it looks like the time has come to sunlight the app, unless someone has more details on the FairPlay setup.

**Comment by dizzzz** [comment]
Thnx buddy for your hard work on the app; I hope the sun will shine again (we *&^&*& paid taxes for the content!) any time soon.....

**Comment by 4np** [comment]
See [PlayerViewController+FairPlay.swift ](https://github.com/4np/TVGemist/blob/master/TVGemist/Player/PlayerViewController%2BFairPlay.swift) for some tests I did. Unfortunately I'm not sure how to authenticate against the license server, most likely you need some private secret for that.
