### ISSUE TITLE
Debug logging regarding constraint satisfaction

### ISSUE THREAD

**Issue by technimad** [4np/TVGemist#2]
## Short description of the issue

When I start the app, I see in the debug window debug logging which mentions a problem with constraint satisfaction.
I don't know if this indicates a real problem, but mentioning this here might help development.

## Issue type

Bug?

## What is actually happening?

While navigating through the list of 'Programma's', the xcode debug window shows logs like:
---
2018-02-22 19:40:25.101 [Debug] [ProgramViewController.swift:48] setupPaginator() > Page 1 of 12 (20 episodes)
2018-02-22 19:40:25.117455+0100 TVGemist[249:116898] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x1c0487d00 UIImageView:0x102f85810.width == 1.77778*UIImageView:0x102f85810.height   (active)>",
    "<NSLayoutConstraint:0x1c04883e0 UILabel:0x102f85a20'NOS Pyeongchang Vandaag'.height == 35   (active)>",
    "<NSLayoutConstraint:0x1c429e0f0 UILabel:0x102f904a0'22 feb. 2018 18:00'.height == 30   (active)>",
    "<NSLayoutConstraint:0x1c0488660 H:[UIImageView:0x102f85810]-(0)-|   (active, names: '|':TVGemist.EpisodeCollectionViewCell:0x102e87ab0 )>",
    "<NSLayoutConstraint:0x1c04886b0 H:|-(0)-[UIImageView:0x102f85810]   (active, names: '|':TVGemist.EpisodeCollectionViewCell:0x102e87ab0 )>",
    "<NSLayoutConstraint:0x1c0488700 V:|-(0)-[UIImageView:0x102f85810]   (active, names: '|':TVGemist.EpisodeCollectionViewCell:0x102e87ab0 )>",
    "<NSLayoutConstraint:0x1c0488750 V:[UIImageView:0x102f85810]-(8)-[UILabel:0x102f85a20'NOS Pyeongchang Vandaag']   (active)>",
    "<NSLayoutConstraint:0x1c0488840 V:[UILabel:0x102f904a0'22 feb. 2018 18:00']-(20)-|   (active, names: '|':TVGemist.EpisodeCollectionViewCell:0x102e87ab0 )>",
    "<NSLayoutConstraint:0x1c0488930 V:[UILabel:0x102f85a20'NOS Pyeongchang Vandaag']-(8)-[UILabel:0x102f904a0'22 feb. 2018 18:00']   (active)>",
    "<NSLayoutConstraint:0x1c429e550 'UIView-Encapsulated-Layout-Height' TVGemist.EpisodeCollectionViewCell:0x102e87ab0.height == 312   (active)>",
    "<NSLayoutConstraint:0x1c429e500 'UIView-Encapsulated-Layout-Width' TVGemist.EpisodeCollectionViewCell:0x102e87ab0.width == 375   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1c04883e0 UILabel:0x102f85a20'NOS Pyeongchang Vandaag'.height == 35   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
---

These messages are repeated multiple times.

## Steps to reproduce

Install app.

## Extra information

Version you are using: 464d593f0639d6fcc09ca3878220898f529ce2bf

tvOS version: most recent (appletv is set to auto update)

Xcode version: 9.2

**Comment by 4np** [comment]
Not really an issue, but something I should take a look at at some point. You can ignore errors like these as this will not break the app. It's merely an issue with the UI constraints and some of them are conflicting so Apple does not know which one to prefer. It might mean the a text label is a bit wider than it should be, or something is positioned a bit differently, but most likely not anything you'd notice.

**Comment by 4np** [comment]
I don't see those Storyboard warnings, closing as this doesn't seem to be an issue (anymore?)...
