### ISSUE TITLE
Build fails: No such module 'NPOKit'

### ISSUE THREAD

**Issue by ghost** [4np/TVGemist#3]
## Short description of the issue
Upon building I get the message: No such module 'NPOKit'. I've followed the installation instructions exactly. Unfortunately I don't know how to fix this as I'm not an Swift developer. Tried to google around without luck.

## Issue type
Enhancement (of documentation)

## What is the expected behaviour?
It should build without problems (tried UitzendingGemist earlier without any problems).

## What is actually happening?
When I try to build it fails with: No such module 'NPOKit'.

## Steps to reproduce
Hit the build button.

## Extra information

Version you are using: I've tried both master and 0.0.3.

tvOS version: Not relevant, because it also doesn't work for simulator.

Xcode version: 9.2 (9C40b)

**Comment by 4np** [comment]
My hunch is that you most likely opened `TVGemist.xcodeproj` instead of `TVGemist.xcworkspace`? You should use the latter :)

**Comment by ghost** [comment]
Ah yes, that's it! It seemed so logical to me to click on that file because it also has a blue icon like Xcode. Anyway, thanks for helping me out and for this great project! 👍
