### ISSUE TITLE
Support for NPO Start content (feature request)

### ISSUE THREAD

**Issue by itavero** [4np/TVGemist#5]
It would be nice if I would be able to log in to the Apple TV app and also view the content that is only available for NPO Start subscribers (like the first seasons of Penoza).
I currently use AirPlay from the official NPO app, but this isn't flawless and I'm missing the subtitles.

**Comment by 4np** [comment]
I agree this would be nice, however I don't see this happening anytime soon :) I'm not an NPO Start subscriber and there's a whole range of new challenges to tackle for implementing this. I won't say never, but don't rely on this feature :) Closing this for now...

**Comment by itavero** [comment]
I already have a lot of side projects I do in my spare time, but perhaps I can find a moment to decompile the Android app and figure out the additional APIs and such myself.

**Comment by 4np** [comment]
Yeah, sounds familiar haha :D But if you can figure out any details that would be of great help 👍

**Comment by 4np** [comment]
Closed the feature request as this deviates too far from the scope of the application.
