### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dizzzz** [4np/TVGemist#7]
## Short description of the issue

Build is failing, see image

```
NPOKit Group
Swift Compiler Error Group
tvOS/TVgemist/Pods/NPOKit/Sources/NPOKit/NPOKit+Live.swift:19:34: Value of type '[LiveComponent]' has no member 'compactMap'
TVgemist/Pods/NPOKit/Sources/NPOKit/NPOKit+Subtitles.swift:81:36: Value of type '[SubtitleLine?]' (aka 'Array<Optional<(number: Int, from: Double, to: Double, text: String)>>') has no member 'compactMap'
```

## Issue type

Compilation error

## What is the expected behaviour?

Project cane be compiled

## What is actually happening?

See image

## Steps to reproduce

Open in code, try to build

## Extra information

Version you are using: a0e60d15a2662b552ea4c1efd81fa20ccbe4004b 

tvOS version: 0.0.3

Xcode version: 9.2
<img width="1143" alt="npokit_live_swift_and_tvgemist_ _-bash_ _80x24" src="https://user-images.githubusercontent.com/1700062/38045721-ed352f7e-32bd-11e8-9961-52f492fda128.png">

**Comment by 4np** [comment]
Yes, you need `Xcode 9.3 beta 4` / `Swift 4.1` which are currently both still in beta and -unfortunately against all expectations- did not get released yesterday after Apple's education event... So either:

- use `Xcode 9.3 beta 4`
- wait for `Xcode 9.3` to be released and stick with [0.0.3](https://github.com/4np/TVGemist/releases/tag/0.0.3) for now
- or change `compactMap` to `flatMap` ([reference](https://github.com/apple/swift-evolution/blob/master/proposals/0187-introduce-filtermap.md)) and try to compile again :)

**Comment by dizzzz** [comment]
ok thnx :-)

**Comment by 4np** [comment]
Xcode 9.3 was just released so I'll be tagging a new release shortly...

<img width="1181" alt="screen shot 2018-03-30 at 09 20 32" src="https://user-images.githubusercontent.com/1049693/38128696-f5b858a8-33fb-11e8-80af-3384d1789878.png">
